server:
  port: 8089
spring:
  application:
    name: security-auth
  datasource:
    url: jdbc:mysql://localhost:3306/zl?serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: 123456
    driver-class: com.mysql.jdbc.Driver
  session:
    store-type: none
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    pool:
      maxTotal: 200
      maxIdle: 50
      maxWaitMillis: 15000
      testOnBorrow: true
      testOnReturn: true
      testWhileIdle: true
      minEvictableIdleTimeMillis: 60000
      timeBetweenEvictionRunsMillis: 3000
      numTestsPerEvictionRun: -1
security:
  basic:
    enabled: true
zl:
  security:
    browser:
      loginPage: /demo-signIn.html